import { describe, expect, vi } from 'vitest'
import { it as mongoIt } from '#vite/fixtures/mongo.js'
import { MongoClient, ObjectId } from 'mongodb'

import { createSummaryLogsRepository } from '#repositories/summary-logs/mongodb.js'
import { createSystemLogsRepository } from '#repositories/system-logs/mongodb.js'
import { createWasteRecordsRepository } from '#repositories/waste-records/mongodb.js'
import { summaryLogFactory } from '#repositories/summary-logs/contract/test-data.js'
import { syncFromSummaryLog } from '#application/waste-records/sync-from-summary-log.js'
import { createInMemorySummaryLogExtractor } from '#application/summary-logs/extractor-inmemory.js'
import { ROW_OUTCOME } from '#domain/summary-logs/table-schemas/validation-pipeline.js'
import { auditSummaryLogSubmit } from '#root/auditing/summary-logs.js'
import { buildSystemLogSubmitters } from '#waste-balances/application/summary-log-submitters.js'
import { computeRebuiltStream } from '#waste-balances/application/compute-rebuilt-stream.js'

import { toStreamSummaryLog } from './run-balance-divergence-diagnostic.js'

vi.mock('@aws-sdk/s3-request-presigner', () => ({
  getSignedUrl: vi.fn()
}))

vi.mock('@defra/cdp-auditing', () => ({
  audit: vi.fn()
}))

vi.mock(
  '#domain/summary-logs/table-schemas/index.js',
  async (importOriginal) => {
    const original = /** @type {Record<string, unknown>} */ (
      await importOriginal()
    )
    return {
      ...original,
      findSchemaForProcessingType: vi.fn().mockReturnValue({
        classifyForWasteBalance: (
          /** @type {Record<string, unknown>} */ data
        ) => ({
          outcome: ROW_OUTCOME.INCLUDED,
          transactionAmount: Number(data.GROSS_WEIGHT) || 0
        })
      })
    }
  }
)

const DATABASE_NAME = 'epr-backend'

const mockS3Config = /** @type {any} */ ({})
const mockLogger = /** @type {any} */ ({
  info: vi.fn(),
  error: vi.fn(),
  warn: vi.fn(),
  debug: vi.fn()
})

const it = mongoIt.extend({
  mongoClient: async ({ db }, use) => {
    // @ts-expect-error vitest fixture types db as union, not string
    const client = await MongoClient.connect(db)
    await use(client)
    await client.close()
  },

  summaryLogsRepository: async ({ mongoClient }, use) => {
    const database = /** @type {import('mongodb').MongoClient} */ (
      mongoClient
    ).db(DATABASE_NAME)
    const factory = await createSummaryLogsRepository(database, mockS3Config)
    await use(factory(mockLogger))
  },

  wasteRecordsRepository: async ({ mongoClient }, use) => {
    const database = /** @type {import('mongodb').MongoClient} */ (
      mongoClient
    ).db(DATABASE_NAME)
    const factory = await createWasteRecordsRepository(database)
    await use(factory())
  },

  systemLogsRepository: async ({ mongoClient }, use) => {
    const database = /** @type {import('mongodb').MongoClient} */ (
      mongoClient
    ).db(DATABASE_NAME)
    const factory = await createSystemLogsRepository(database)
    await use(factory(mockLogger))
  }
})

describe('balance divergence diagnostic (integration)', () => {
  it('stream replay produces correct creditTotal when waste records are seeded through the real write path', async ({
    summaryLogsRepository,
    wasteRecordsRepository
  }) => {
    const slRepo =
      /** @type {import('#repositories/summary-logs/port.js').SummaryLogsRepository} */ (
        summaryLogsRepository
      )
    const wrRepo =
      /** @type {import('#repositories/waste-records/port.js').WasteRecordsRepository} */ (
        wasteRecordsRepository
      )

    const organisationId = new ObjectId().toString()
    const registrationId = new ObjectId().toString()
    const docId = new ObjectId().toString()

    // 1. Seed a submitted summary log (file.id is auto-generated by the factory)
    await slRepo.insert(
      docId,
      summaryLogFactory.submitted({
        organisationId,
        registrationId,
        submittedAt: '2025-01-15T10:00:00.000Z'
      })
    )

    // 2. Read back via findAllByOrgReg — the same query the diagnostic uses
    const summaryLogDocs = await slRepo.findAllByOrgReg(
      organisationId,
      registrationId
    )
    const fileId = summaryLogDocs[0].summaryLog.file.id

    // Sanity: the document _id and file.id are different identifiers
    expect(summaryLogDocs[0].id).toBe(docId)
    expect(docId).not.toBe(fileId)

    // 3. Seed waste records through the real production write path.
    //    syncFromSummaryLog sets versions[].summaryLog.id = summaryLog.file.id
    //    via transformToWasteRecords — no hand-crafted join key.
    /** @type {any} */
    const parsedData = {
      meta: { PROCESSING_TYPE: { value: 'REPROCESSOR_INPUT' } },
      data: {
        RECEIVED_LOADS_FOR_REPROCESSING: {
          location: { sheet: 'Sheet1', row: 1, column: 'A' },
          headers: ['ROW_ID', 'GROSS_WEIGHT'],
          rows: [{ rowNumber: 2, values: ['row-1', 202.47] }]
        }
      }
    }

    const sync = /** @type {any} */ (syncFromSummaryLog)({
      extractor: createInMemorySummaryLogExtractor({ [fileId]: parsedData }),
      wasteRecordRepository: wrRepo,
      organisationsRepository: {
        findRegistrationById: async () => null
      },
      overseasSitesRepository: {
        findByIds: async () => []
      }
    })

    await sync(
      {
        file: { id: fileId, uri: 's3://bucket/key' },
        organisationId,
        registrationId
      },
      { id: 'test-user', email: 'test@example.com', scope: [] }
    )

    // 4. Read waste records back — versions[].summaryLog.id was set by production code
    const wasteRecords = await wrRepo.findByRegistration(
      organisationId,
      registrationId
    )
    expect(wasteRecords).toHaveLength(1)
    expect(wasteRecords[0].versions[0].summaryLog.id).toBe(fileId)

    // 5. Map summary logs via the production helper, then replay the stream
    const summaryLogs = summaryLogDocs.map(toStreamSummaryLog)

    const result = computeRebuiltStream({
      accreditation: { id: 'acc-1' },
      registrationId,
      organisationId,
      wasteRecords,
      prns: [],
      overseasSites: {},
      summaryLogs
    })

    // If the mapping passes the wrong ID (doc._id instead of file.id),
    // reconstructDataAtSubmission returns null for every record and
    // creditTotal is 0 — the exact bug we observed in production
    expect(result.amount).toBe(202.47)
    expect(result.events).toHaveLength(1)
  })

  it('attributes the submission to the submitter recorded by the real submit audit, bridging document id to file id', async ({
    summaryLogsRepository,
    wasteRecordsRepository,
    systemLogsRepository
  }) => {
    const slRepo =
      /** @type {import('#repositories/summary-logs/port.js').SummaryLogsRepository} */ (
        summaryLogsRepository
      )
    const wrRepo =
      /** @type {import('#repositories/waste-records/port.js').WasteRecordsRepository} */ (
        wasteRecordsRepository
      )
    const sysRepo =
      /** @type {import('#repositories/system-logs/port.js').SystemLogsRepository} */ (
        systemLogsRepository
      )

    const organisationId = new ObjectId().toString()
    const registrationId = new ObjectId().toString()
    const docId = new ObjectId().toString()

    // 1. Submit a summary log: insert the document, then record the submit
    //    audit through the real auditing path. The audit stamps
    //    context.summaryLogId with the DOCUMENT id, not the file id.
    await slRepo.insert(
      docId,
      summaryLogFactory.submitted({
        organisationId,
        registrationId,
        submittedAt: '2025-01-15T10:00:00.000Z'
      })
    )

    const summaryLogDocs = await slRepo.findAllByOrgReg(
      organisationId,
      registrationId
    )
    const fileId = summaryLogDocs[0].summaryLog.file.id
    expect(summaryLogDocs[0].id).toBe(docId)
    expect(docId).not.toBe(fileId)

    const submitter = {
      id: 'user-1',
      email: 'alice@example.com',
      scope: ['standardUser']
    }
    await auditSummaryLogSubmit(
      /** @type {any} */ ({
        auth: { credentials: submitter },
        systemLogsRepository: sysRepo
      }),
      { summaryLogId: docId, organisationId, registrationId }
    )

    // 2. Seed waste records through the real write path — versions[].summaryLog.id
    //    is set to the file id, the other half of the namespace the bridge spans.
    /** @type {any} */
    const parsedData = {
      meta: { PROCESSING_TYPE: { value: 'REPROCESSOR_INPUT' } },
      data: {
        RECEIVED_LOADS_FOR_REPROCESSING: {
          location: { sheet: 'Sheet1', row: 1, column: 'A' },
          headers: ['ROW_ID', 'GROSS_WEIGHT'],
          rows: [{ rowNumber: 2, values: ['row-1', 202.47] }]
        }
      }
    }

    const sync = /** @type {any} */ (syncFromSummaryLog)({
      extractor: createInMemorySummaryLogExtractor({ [fileId]: parsedData }),
      wasteRecordRepository: wrRepo,
      organisationsRepository: { findRegistrationById: async () => null },
      overseasSitesRepository: { findByIds: async () => [] }
    })

    await sync(
      {
        file: { id: fileId, uri: 's3://bucket/key' },
        organisationId,
        registrationId
      },
      { id: 'test-user', email: 'test@example.com', scope: [] }
    )

    const wasteRecords = await wrRepo.findByRegistration(
      organisationId,
      registrationId
    )

    // 3. Read the submit audit back and bridge document id -> file id. The audit
    //    keys on docId; the bridge resolves it to the version's file id.
    const submitActors = await sysRepo.findSummaryLogSubmitActors([docId])
    expect(submitActors).toEqual([
      { summaryLogId: docId, createdBy: submitter }
    ])

    const submitters = buildSystemLogSubmitters({
      submitActors,
      summaryLogDocs
    })
    expect(submitters.get(fileId)).toEqual({
      id: 'user-1',
      name: 'alice@example.com'
    })

    // 4. Migrate: replay the stream with the recovered submitter attached and
    //    confirm the event is credited to the real submitter, not the backfill
    //    actor.
    const summaryLogs = summaryLogDocs.map(toStreamSummaryLog).map((sl) => {
      const recovered = submitters.get(sl.id)
      return recovered ? { ...sl, submittedBy: recovered } : sl
    })

    const result = computeRebuiltStream({
      accreditation: { id: 'acc-1' },
      registrationId,
      organisationId,
      wasteRecords,
      prns: [],
      overseasSites: {},
      summaryLogs
    })

    expect(result.amount).toBe(202.47)
    expect(result.backfilledActorCount).toBe(0)
    expect(result.events[0].createdBy).toEqual({
      id: 'user-1',
      name: 'alice@example.com'
    })
  })
})
