import Joi from 'joi'

/**
 * Constants for SONAR...
 */
const EWC_CODE_REGEX = /^\d{2} \d{2} \d{2}$/
const MIN_ROW_ID = 10000
const ZERO = 0

const IS_REQUIRED = 'is required'
const MUST_BE_A_VALID_DATE = 'must be a valid date'
const MUST_BE_A_NUMBER = 'must be a number'
const MUST_BE_A_STRING = 'must be a string'
const MUST_BE_GREATER_THAN_ZERO = 'must be greater than 0'
const MUST_BE_LESS_THAN_ONE = 'must be less than 1'

/**
 * Failure schema for RECEIVED_LOADS_FOR_REPROCESSING table
 *
 * ROW_ID is auto-generated by the spreadsheet starting at 10000 and should
 * not be edited by users. Invalid ROW_IDs indicate tampering or corruption
 * and produce failures that reject the entire spreadsheet.
 */
export const RECEIVED_LOADS_FOR_REPROCESSING_FAILURE_SCHEMA = Joi.object({
  ROW_ID: Joi.number().required().min(MIN_ROW_ID).messages({
    'number.base': MUST_BE_A_NUMBER,
    'number.min': 'must be at least 10000',
    'any.required': IS_REQUIRED
  })
})
  .unknown(true)
  .prefs({ abortEarly: false })

/**
 * Concern schema for RECEIVED_LOADS_FOR_REPROCESSING table
 *
 * Validates all fields except ROW_ID (which is validated by the failure schema).
 * Issues produce concerns that mark specific rows as invalid but don't block
 * submission of the entire spreadsheet.
 *
 * Optimizations applied:
 * - Schema reuse: Single schema object shared across all row validations
 * - Preferences pre-set: abortEarly=false configured once on schema
 * - Pattern extraction: Common validation patterns (e.g., positive numbers) reused
 * - Unknown fields: .unknown(true) allows extra spreadsheet columns
 */
export const RECEIVED_LOADS_FOR_REPROCESSING_CONCERN_SCHEMA = Joi.object({
  DATE_RECEIVED_FOR_REPROCESSING: Joi.date().required().messages({
    'date.base': MUST_BE_A_VALID_DATE,
    'any.required': IS_REQUIRED
  }),
  EWC_CODE: Joi.string().required().pattern(EWC_CODE_REGEX).messages({
    'string.base': MUST_BE_A_STRING,
    'string.pattern.base': 'must be in format "XX XX XX" (e.g., "03 03 08")',
    'any.required': IS_REQUIRED
  }),
  GROSS_WEIGHT: Joi.number().required().greater(ZERO).messages({
    'number.base': MUST_BE_A_NUMBER,
    'number.greater': MUST_BE_GREATER_THAN_ZERO,
    'any.required': IS_REQUIRED
  }),
  TARE_WEIGHT: Joi.number().required().greater(ZERO).messages({
    'number.base': MUST_BE_A_NUMBER,
    'number.greater': MUST_BE_GREATER_THAN_ZERO,
    'any.required': IS_REQUIRED
  }),
  PALLET_WEIGHT: Joi.number().required().greater(ZERO).messages({
    'number.base': MUST_BE_A_NUMBER,
    'number.greater': MUST_BE_GREATER_THAN_ZERO,
    'any.required': IS_REQUIRED
  }),
  NET_WEIGHT: Joi.number().required().greater(ZERO).messages({
    'number.base': MUST_BE_A_NUMBER,
    'number.greater': MUST_BE_GREATER_THAN_ZERO,
    'any.required': IS_REQUIRED
  }),
  BAILING_WIRE_PROTOCOL: Joi.string().required().messages({
    'string.base': MUST_BE_A_STRING,
    'any.required': IS_REQUIRED
  }),
  HOW_DID_YOU_CALCULATE_RECYCLABLE_PROPORTION: Joi.string()
    .required()
    .messages({
      'string.base': MUST_BE_A_STRING,
      'any.required': IS_REQUIRED
    }),
  WEIGHT_OF_NON_TARGET_MATERIALS: Joi.number()
    .required()
    .greater(ZERO)
    .messages({
      'number.base': MUST_BE_A_NUMBER,
      'number.greater': MUST_BE_GREATER_THAN_ZERO,
      'any.required': IS_REQUIRED
    }),
  RECYCLABLE_PROPORTION_PERCENTAGE: Joi.number()
    .required()
    .greater(ZERO)
    .less(1)
    .messages({
      'number.base': MUST_BE_A_NUMBER,
      'number.greater': MUST_BE_GREATER_THAN_ZERO,
      'number.less': MUST_BE_LESS_THAN_ONE,
      'any.required': IS_REQUIRED
    }),
  TONNAGE_RECEIVED_FOR_RECYCLING: Joi.number().required().messages({
    'number.base': MUST_BE_A_NUMBER,
    'any.required': IS_REQUIRED
  })
})
  .unknown(true)
  .prefs({ abortEarly: false })

/**
 * Empty schema that accepts any data
 * Used for tables that don't yet have validation rules defined
 */
export const EMPTY_SCHEMA = Joi.object({})
  .unknown(true)
  .prefs({ abortEarly: false })
