/**
 * Field name constants for exporter-registered-only tables
 *
 * Single source of truth for field names used throughout schemas in this folder.
 * Registered-only exporters have simplified column sets compared to accredited exporters:
 * - No detailed weighing (gross/tare/pallet/bailing wire)
 * - No waste classification (EWC codes, waste descriptions, PRN/PERN)
 * - Monthly granularity (MONTH_RECEIVED_FOR_EXPORT) instead of daily dates
 * - Supplier info included (borrowed from reprocessor pattern)
 * - Export-specific fields split into separate LOADS_EXPORTED table
 */

/**
 * ROW_ID minimum values for EXPORTER_REGISTERED_ONLY tables
 *
 * Different tables have different ROW_ID starting offsets to ensure
 * ROW_ID values do not overlap across any table in the spreadsheet.
 */
export const ROW_ID_MINIMUMS = Object.freeze({
  RECEIVED_LOADS_FOR_EXPORT: 1000,
  LOADS_EXPORTED: 2000,
  SENT_ON_LOADS: 4000
})

export const RECEIVED_LOADS_FIELDS = Object.freeze({
  ROW_ID: 'ROW_ID',
  MONTH_RECEIVED_FOR_EXPORT: 'MONTH_RECEIVED_FOR_EXPORT',
  SUPPLIER_NAME: 'SUPPLIER_NAME',
  SUPPLIER_ADDRESS: 'SUPPLIER_ADDRESS',
  SUPPLIER_POSTCODE: 'SUPPLIER_POSTCODE',
  SUPPLIER_EMAIL: 'SUPPLIER_EMAIL',
  SUPPLIER_PHONE_NUMBER: 'SUPPLIER_PHONE_NUMBER',
  ACTIVITIES_CARRIED_OUT_BY_SUPPLIER: 'ACTIVITIES_CARRIED_OUT_BY_SUPPLIER',
  NET_WEIGHT: 'NET_WEIGHT',
  HOW_DID_YOU_CALCULATE_RECYCLABLE_PROPORTION:
    'HOW_DID_YOU_CALCULATE_RECYCLABLE_PROPORTION',
  RECYCLABLE_PROPORTION_PERCENTAGE: 'RECYCLABLE_PROPORTION_PERCENTAGE',
  TONNAGE_RECEIVED_FOR_EXPORT: 'TONNAGE_RECEIVED_FOR_EXPORT'
})

export const LOADS_EXPORTED_FIELDS = Object.freeze({
  ROW_ID: 'ROW_ID',
  TONNAGE_OF_UK_PACKAGING_WASTE_EXPORTED:
    'TONNAGE_OF_UK_PACKAGING_WASTE_EXPORTED',
  DATE_OF_EXPORT: 'DATE_OF_EXPORT',
  OSR_ID: 'OSR_ID',
  BASEL_EXPORT_CODE: 'BASEL_EXPORT_CODE',
  WAS_THE_WASTE_REFUSED: 'WAS_THE_WASTE_REFUSED',
  WAS_THE_WASTE_STOPPED: 'WAS_THE_WASTE_STOPPED',
  DATE_THE_REFUSED_STOPPED_WASTE_REPATRIATED:
    'DATE_THE_REFUSED_STOPPED_WASTE_REPATRIATED',
  OSR_NAME: 'OSR_NAME',
  OSR_COUNTRY: 'OSR_COUNTRY',
  CUSTOMS_CODES: 'CUSTOMS_CODES',
  CONTAINER_NUMBER: 'CONTAINER_NUMBER'
})

export const SENT_ON_LOADS_FIELDS = Object.freeze({
  ROW_ID: 'ROW_ID',
  DATE_LOAD_LEFT_SITE: 'DATE_LOAD_LEFT_SITE',
  TONNAGE_OF_UK_PACKAGING_WASTE_SENT_ON:
    'TONNAGE_OF_UK_PACKAGING_WASTE_SENT_ON',
  FINAL_DESTINATION_FACILITY_TYPE: 'FINAL_DESTINATION_FACILITY_TYPE',
  FINAL_DESTINATION_NAME: 'FINAL_DESTINATION_NAME',
  FINAL_DESTINATION_ADDRESS: 'FINAL_DESTINATION_ADDRESS',
  FINAL_DESTINATION_POSTCODE: 'FINAL_DESTINATION_POSTCODE'
})
