/**
 * Field name constants for reprocessor-output tables
 *
 * Single source of truth for field names used throughout schemas in this folder.
 */

// Re-export shared fields (identical across reprocessor-input and reprocessor-output)
export { RECEIVED_LOADS_FOR_REPROCESSING_FIELDS as RECEIVED_LOADS_FIELDS } from '../shared/index.js'

/**
 * ROW_ID minimum values for REPROCESSOR_OUTPUT tables
 *
 * Different tables have different ROW_ID starting offsets to ensure
 * ROW_ID values do not overlap across any table in the spreadsheet.
 */
export const ROW_ID_MINIMUMS = Object.freeze({
  RECEIVED_LOADS_FOR_REPROCESSING: 1000,
  REPROCESSED_LOADS: 3000,
  SENT_ON_LOADS: 5000
})

export const REPROCESSED_LOADS_FIELDS = Object.freeze({
  ROW_ID: 'ROW_ID',
  DATE_LOAD_LEFT_SITE: 'DATE_LOAD_LEFT_SITE',
  PRODUCT_TONNAGE: 'PRODUCT_TONNAGE',
  UK_PACKAGING_WEIGHT_PERCENTAGE: 'UK_PACKAGING_WEIGHT_PERCENTAGE',
  PRODUCT_UK_PACKAGING_WEIGHT_PROPORTION:
    'PRODUCT_UK_PACKAGING_WEIGHT_PROPORTION',
  ADD_PRODUCT_WEIGHT: 'ADD_PRODUCT_WEIGHT'
})

export const SENT_ON_LOADS_FIELDS = Object.freeze({
  ROW_ID: 'ROW_ID',
  DATE_LOAD_LEFT_SITE: 'DATE_LOAD_LEFT_SITE',
  TONNAGE_OF_UK_PACKAGING_WASTE_SENT_ON:
    'TONNAGE_OF_UK_PACKAGING_WASTE_SENT_ON',
  FINAL_DESTINATION_FACILITY_TYPE: 'FINAL_DESTINATION_FACILITY_TYPE',
  FINAL_DESTINATION_NAME: 'FINAL_DESTINATION_NAME',
  FINAL_DESTINATION_ADDRESS: 'FINAL_DESTINATION_ADDRESS',
  FINAL_DESTINATION_POSTCODE: 'FINAL_DESTINATION_POSTCODE',
  FINAL_DESTINATION_EMAIL: 'FINAL_DESTINATION_EMAIL',
  FINAL_DESTINATION_PHONE: 'FINAL_DESTINATION_PHONE',
  YOUR_REFERENCE: 'YOUR_REFERENCE',
  DESCRIPTION_WASTE: 'DESCRIPTION_WASTE'
})
