export {
  EPR_PREFIX,
  META_PREFIX,
  DATA_PREFIX,
  SKIP_COLUMN,
  SKIP_ROW_TEXT,
  PLACEHOLDER_TEXT,
  MATERIAL_PLACEHOLDER_TEXT,
  isEprMarker
} from './markers.js'

export {
  SUMMARY_LOG_META_FIELDS,
  PROCESSING_TYPES,
  PROCESSING_TYPE_TO_WASTE_PROCESSING_TYPE
} from './meta-fields.js'
