import { describe } from 'vitest'
import { it as baseIt } from '#vite/fixtures/cdp-uploader.js'
import { testUploadsRepositoryContract } from './port.contract.js'

const POLL_INTERVAL_MS = 500
const MAX_POLL_ATTEMPTS = 30

async function waitForUploadComplete(cdpUploaderUrl, uploadId) {
  for (let attempt = 0; attempt < MAX_POLL_ATTEMPTS; attempt++) {
    const response = await fetch(`${cdpUploaderUrl}/status/${uploadId}`)
    const status = await response.json()

    if (status.uploadStatus === 'rejected') {
      throw new Error(`Upload was rejected: ${JSON.stringify(status)}`)
    }

    if (status.uploadStatus === 'ready') {
      return status
    }

    await new Promise((resolve) => setTimeout(resolve, POLL_INTERVAL_MS))
  }

  throw new Error(
    `Upload did not complete within ${MAX_POLL_ATTEMPTS * POLL_INTERVAL_MS}ms`
  )
}

const it = baseIt.extend({
  performUpload: async ({ uploadsRepository, cdpUploaderStack }, use) => {
    await use(async (uploadId, buffer) => {
      // Get the upload URL from a fresh initiation to find the path pattern
      // (the uploadId was already generated by the contract test's initiate call)
      const uploadUrlPath = `/upload-and-scan/${uploadId}`

      const formData = new FormData()
      formData.append(
        'file',
        new Blob([buffer], {
          type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        }),
        'summary-log.xlsx'
      )

      const uploadResponse = await fetch(
        `${cdpUploaderStack.cdpUploader.url}${uploadUrlPath}`,
        {
          method: 'POST',
          body: formData,
          redirect: 'manual'
        }
      )

      if (uploadResponse.status !== 302) {
        throw new Error(
          `Expected 302 redirect from CDP Uploader, got ${uploadResponse.status}`
        )
      }

      // Wait for virus scan to complete
      const status = await waitForUploadComplete(
        cdpUploaderStack.cdpUploader.url,
        uploadId
      )

      const s3Uri = `s3://re-ex-summary-logs/${status.form.file.s3Key}`

      return { s3Uri }
    })
  }
})

describe('CDP Uploader uploads repository', () => {
  testUploadsRepositoryContract(it)
})
