/**
 * Field name constants for reprocessor-input tables
 *
 * Single source of truth for field names used throughout schemas in this folder.
 */

/**
 * ROW_ID minimum values for REPROCESSOR_INPUT tables
 *
 * Different tables have different ROW_ID starting offsets to ensure
 * ROW_ID values do not overlap across any table in the spreadsheet.
 */
export const ROW_ID_MINIMUMS = Object.freeze({
  RECEIVED_LOADS_FOR_REPROCESSING: 1000,
  REPROCESSED_LOADS: 4000,
  SENT_ON_LOADS: 5000
})

export const RECEIVED_LOADS_FIELDS = Object.freeze({
  ROW_ID: 'ROW_ID',
  DATE_RECEIVED_FOR_REPROCESSING: 'DATE_RECEIVED_FOR_REPROCESSING',
  EWC_CODE: 'EWC_CODE',
  DESCRIPTION_WASTE: 'DESCRIPTION_WASTE',
  WERE_PRN_OR_PERN_ISSUED_ON_THIS_WASTE:
    'WERE_PRN_OR_PERN_ISSUED_ON_THIS_WASTE',
  GROSS_WEIGHT: 'GROSS_WEIGHT',
  TARE_WEIGHT: 'TARE_WEIGHT',
  PALLET_WEIGHT: 'PALLET_WEIGHT',
  NET_WEIGHT: 'NET_WEIGHT',
  BAILING_WIRE_PROTOCOL: 'BAILING_WIRE_PROTOCOL',
  HOW_DID_YOU_CALCULATE_RECYCLABLE_PROPORTION:
    'HOW_DID_YOU_CALCULATE_RECYCLABLE_PROPORTION',
  WEIGHT_OF_NON_TARGET_MATERIALS: 'WEIGHT_OF_NON_TARGET_MATERIALS',
  RECYCLABLE_PROPORTION_PERCENTAGE: 'RECYCLABLE_PROPORTION_PERCENTAGE',
  TONNAGE_RECEIVED_FOR_RECYCLING: 'TONNAGE_RECEIVED_FOR_RECYCLING'
})

export const SENT_ON_LOADS_FIELDS = Object.freeze({
  ROW_ID: 'ROW_ID',
  DATE_LOAD_LEFT_SITE: 'DATE_LOAD_LEFT_SITE',
  TONNAGE_OF_UK_PACKAGING_WASTE_SENT_ON: 'TONNAGE_OF_UK_PACKAGING_WASTE_SENT_ON'
})
