/**
 * Shared field name constants used across multiple table schema types
 *
 * Fields that are identical across exporter, reprocessor-input, and
 * reprocessor-output schemas should be defined here to avoid duplication.
 */

/**
 * SENT_ON_LOADS field names - identical across exporter and reprocessor-input.
 * Reprocessor-output has a different set (missing EWC_CODE, WEIGHBRIDGE_TICKET).
 */
export const SENT_ON_LOADS_FIELDS = Object.freeze({
  ROW_ID: 'ROW_ID',
  DATE_LOAD_LEFT_SITE: 'DATE_LOAD_LEFT_SITE',
  TONNAGE_OF_UK_PACKAGING_WASTE_SENT_ON:
    'TONNAGE_OF_UK_PACKAGING_WASTE_SENT_ON',
  FINAL_DESTINATION_FACILITY_TYPE: 'FINAL_DESTINATION_FACILITY_TYPE',
  FINAL_DESTINATION_NAME: 'FINAL_DESTINATION_NAME',
  FINAL_DESTINATION_ADDRESS: 'FINAL_DESTINATION_ADDRESS',
  FINAL_DESTINATION_POSTCODE: 'FINAL_DESTINATION_POSTCODE',
  FINAL_DESTINATION_EMAIL: 'FINAL_DESTINATION_EMAIL',
  FINAL_DESTINATION_PHONE: 'FINAL_DESTINATION_PHONE',
  YOUR_REFERENCE: 'YOUR_REFERENCE',
  DESCRIPTION_WASTE: 'DESCRIPTION_WASTE',
  EWC_CODE: 'EWC_CODE',
  WEIGHBRIDGE_TICKET: 'WEIGHBRIDGE_TICKET'
})

/**
 * RECEIVED_LOADS field names for reprocessing variants.
 * Identical across reprocessor-input and reprocessor-output.
 */
export const RECEIVED_LOADS_FOR_REPROCESSING_FIELDS = Object.freeze({
  ROW_ID: 'ROW_ID',
  DATE_RECEIVED_FOR_REPROCESSING: 'DATE_RECEIVED_FOR_REPROCESSING',
  EWC_CODE: 'EWC_CODE',
  DESCRIPTION_WASTE: 'DESCRIPTION_WASTE',
  WERE_PRN_OR_PERN_ISSUED_ON_THIS_WASTE:
    'WERE_PRN_OR_PERN_ISSUED_ON_THIS_WASTE',
  GROSS_WEIGHT: 'GROSS_WEIGHT',
  TARE_WEIGHT: 'TARE_WEIGHT',
  PALLET_WEIGHT: 'PALLET_WEIGHT',
  NET_WEIGHT: 'NET_WEIGHT',
  BAILING_WIRE_PROTOCOL: 'BAILING_WIRE_PROTOCOL',
  HOW_DID_YOU_CALCULATE_RECYCLABLE_PROPORTION:
    'HOW_DID_YOU_CALCULATE_RECYCLABLE_PROPORTION',
  WEIGHT_OF_NON_TARGET_MATERIALS: 'WEIGHT_OF_NON_TARGET_MATERIALS',
  RECYCLABLE_PROPORTION_PERCENTAGE: 'RECYCLABLE_PROPORTION_PERCENTAGE',
  TONNAGE_RECEIVED_FOR_RECYCLING: 'TONNAGE_RECEIVED_FOR_RECYCLING',
  SUPPLIER_NAME: 'SUPPLIER_NAME',
  SUPPLIER_ADDRESS: 'SUPPLIER_ADDRESS',
  SUPPLIER_POSTCODE: 'SUPPLIER_POSTCODE',
  SUPPLIER_EMAIL: 'SUPPLIER_EMAIL',
  SUPPLIER_PHONE_NUMBER: 'SUPPLIER_PHONE_NUMBER',
  ACTIVITIES_CARRIED_OUT_BY_SUPPLIER: 'ACTIVITIES_CARRIED_OUT_BY_SUPPLIER',
  YOUR_REFERENCE: 'YOUR_REFERENCE',
  WEIGHBRIDGE_TICKET: 'WEIGHBRIDGE_TICKET',
  CARRIER_NAME: 'CARRIER_NAME',
  CBD_REG_NUMBER: 'CBD_REG_NUMBER',
  CARRIER_VEHICLE_REGISTRATION_NUMBER: 'CARRIER_VEHICLE_REGISTRATION_NUMBER'
})
