import Joi from 'joi'
import { MESSAGES } from './joi-messages.js'

/**
 * Creates a Joi schema for ROW_ID validation
 *
 * ROW_ID is auto-generated by the spreadsheet. Different tables have
 * different starting offsets to ensure ROW_ID values do not overlap
 * across any table in any spreadsheet.
 *
 * Invalid ROW_IDs indicate tampering or corruption and produce
 * failures (VAL010) that reject the entire spreadsheet.
 *
 * @param {number} minRowId - Minimum valid ROW_ID for this table
 * @returns {Joi.NumberSchema} Joi schema for ROW_ID
 */
export const createRowIdSchema = (minRowId) => {
  return Joi.number()
    .integer()
    .min(minRowId)
    .messages({
      'number.base': MESSAGES.MUST_BE_A_NUMBER,
      'number.integer': 'must be an integer',
      'number.min': `must be at least ${minRowId}`
    })
}
