import Joi from 'joi'
import { MESSAGES, CONSTANTS } from './joi-messages.js'

/**
 * Creates a Joi schema for ROW_ID validation
 *
 * ROW_ID is auto-generated by the spreadsheet starting at 10000.
 * Invalid ROW_IDs indicate tampering or corruption and produce
 * failures (VAL010) that reject the entire spreadsheet.
 *
 * @returns {Joi.NumberSchema} Joi schema for ROW_ID
 */
export const createRowIdSchema = () => {
  return Joi.number().integer().min(CONSTANTS.MIN_ROW_ID).messages({
    'number.base': MESSAGES.MUST_BE_A_NUMBER,
    'number.integer': 'must be an integer',
    'number.min': MESSAGES.MUST_BE_AT_LEAST_10000
  })
}
