/**
 * Field name constants for exporter tables
 *
 * Single source of truth for field names used throughout schemas in this folder.
 */

// Re-export shared fields (identical across exporter and reprocessor-input)
export { SENT_ON_LOADS_FIELDS } from '../shared/index.js'

/**
 * ROW_ID minimum values for EXPORTER tables
 *
 * Different tables have different ROW_ID starting offsets to ensure
 * ROW_ID values do not overlap across any table in the spreadsheet.
 */
export const ROW_ID_MINIMUMS = Object.freeze({
  RECEIVED_LOADS_FOR_EXPORT: 1000,
  SENT_ON_LOADS: 4000
})

export const RECEIVED_LOADS_FIELDS = Object.freeze({
  ROW_ID: 'ROW_ID',
  DATE_RECEIVED_FOR_EXPORT: 'DATE_RECEIVED_FOR_EXPORT',
  EWC_CODE: 'EWC_CODE',
  DESCRIPTION_WASTE: 'DESCRIPTION_WASTE',
  WERE_PRN_OR_PERN_ISSUED_ON_THIS_WASTE:
    'WERE_PRN_OR_PERN_ISSUED_ON_THIS_WASTE',
  GROSS_WEIGHT: 'GROSS_WEIGHT',
  TARE_WEIGHT: 'TARE_WEIGHT',
  PALLET_WEIGHT: 'PALLET_WEIGHT',
  NET_WEIGHT: 'NET_WEIGHT',
  BAILING_WIRE_PROTOCOL: 'BAILING_WIRE_PROTOCOL',
  HOW_DID_YOU_CALCULATE_RECYCLABLE_PROPORTION:
    'HOW_DID_YOU_CALCULATE_RECYCLABLE_PROPORTION',
  WEIGHT_OF_NON_TARGET_MATERIALS: 'WEIGHT_OF_NON_TARGET_MATERIALS',
  RECYCLABLE_PROPORTION_PERCENTAGE: 'RECYCLABLE_PROPORTION_PERCENTAGE',
  TONNAGE_RECEIVED_FOR_EXPORT: 'TONNAGE_RECEIVED_FOR_EXPORT',
  TONNAGE_OF_UK_PACKAGING_WASTE_EXPORTED:
    'TONNAGE_OF_UK_PACKAGING_WASTE_EXPORTED',
  DATE_OF_EXPORT: 'DATE_OF_EXPORT',
  BASEL_EXPORT_CODE: 'BASEL_EXPORT_CODE',
  CUSTOMS_CODES: 'CUSTOMS_CODES',
  CONTAINER_NUMBER: 'CONTAINER_NUMBER',
  DATE_RECEIVED_BY_OSR: 'DATE_RECEIVED_BY_OSR',
  OSR_ID: 'OSR_ID',
  DID_WASTE_PASS_THROUGH_AN_INTERIM_SITE:
    'DID_WASTE_PASS_THROUGH_AN_INTERIM_SITE',
  INTERIM_SITE_ID: 'INTERIM_SITE_ID',
  TONNAGE_PASSED_INTERIM_SITE_RECEIVED_BY_OSR:
    'TONNAGE_PASSED_INTERIM_SITE_RECEIVED_BY_OSR',
  EXPORT_CONTROLS: 'EXPORT_CONTROLS'
})
