/**
 * Severity levels for validation issues
 */
export const VALIDATION_SEVERITY = Object.freeze({
  FATAL: 'fatal',
  ERROR: 'error',
  WARNING: 'warning'
})

/**
 * Categories of validation issues
 */
export const VALIDATION_CATEGORY = Object.freeze({
  PARSING: 'parsing',
  TECHNICAL: 'technical',
  BUSINESS: 'business'
})

/**
 * Error codes for validation issues
 * These codes are used for i18n/translation on the client side
 * See ADR 0020 for complete documentation
 */
export const VALIDATION_CODE = Object.freeze({
  // Meta-level validation codes - syntax (from Joi validation)
  REGISTRATION_REQUIRED: 'REGISTRATION_REQUIRED',
  MATERIAL_REQUIRED: 'MATERIAL_REQUIRED',
  PROCESSING_TYPE_REQUIRED: 'PROCESSING_TYPE_REQUIRED',
  PROCESSING_TYPE_INVALID: 'PROCESSING_TYPE_INVALID',
  TEMPLATE_VERSION_REQUIRED: 'TEMPLATE_VERSION_REQUIRED',
  TEMPLATE_VERSION_INVALID: 'TEMPLATE_VERSION_INVALID',

  // Meta-level validation codes - business rules
  REGISTRATION_DATA_INVALID: 'REGISTRATION_DATA_INVALID',
  REGISTRATION_MISMATCH: 'REGISTRATION_MISMATCH',
  PROCESSING_TYPE_DATA_INVALID: 'PROCESSING_TYPE_DATA_INVALID',
  PROCESSING_TYPE_MISMATCH: 'PROCESSING_TYPE_MISMATCH',
  MATERIAL_DATA_INVALID: 'MATERIAL_DATA_INVALID',
  MATERIAL_MISMATCH: 'MATERIAL_MISMATCH',
  ACCREDITATION_MISSING: 'ACCREDITATION_MISSING',
  ACCREDITATION_MISMATCH: 'ACCREDITATION_MISMATCH',
  ACCREDITATION_UNEXPECTED: 'ACCREDITATION_UNEXPECTED',

  // Data-level validation codes
  HEADER_REQUIRED: 'HEADER_REQUIRED',
  FIELD_REQUIRED: 'FIELD_REQUIRED',
  INVALID_TYPE: 'INVALID_TYPE',
  VALUE_OUT_OF_RANGE: 'VALUE_OUT_OF_RANGE',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_DATE: 'INVALID_DATE',
  SEQUENTIAL_ROW_REMOVED: 'SEQUENTIAL_ROW_REMOVED',

  // File upload validation codes (from CDP Uploader rejection)
  FILE_VIRUS_DETECTED: 'FILE_VIRUS_DETECTED',
  FILE_EMPTY: 'FILE_EMPTY',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_WRONG_TYPE: 'FILE_WRONG_TYPE',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_DOWNLOAD_FAILED: 'FILE_DOWNLOAD_FAILED',
  FILE_REJECTED: 'FILE_REJECTED', // Fallback for unknown upload errors

  // Generic/fallback codes
  VALIDATION_FALLBACK_ERROR: 'VALIDATION_FALLBACK_ERROR', // Unmapped Joi validation types
  VALIDATION_SYSTEM_ERROR: 'VALIDATION_SYSTEM_ERROR' // System failures during validation
})
