export const EXPORTER_FIELD = Object.freeze({
  DATE_OF_EXPORT: 'DATE_OF_EXPORT',
  PRN_ISSUED: 'WERE_PRN_OR_PERN_ISSUED_ON_THIS_WASTE',
  INTERIM_SITE: 'DID_WASTE_PASS_THROUGH_AN_INTERIM_SITE',
  INTERIM_TONNAGE: 'TONNAGE_PASSED_INTERIM_SITE_RECEIVED_BY_OSR',
  EXPORT_TONNAGE: 'TONNAGE_OF_UK_PACKAGING_WASTE_EXPORTED'
})

export const REPROCESSOR_INPUT_FIELD = Object.freeze({
  DATE_RECEIVED: 'DATE_RECEIVED_FOR_REPROCESSING',
  PRN_ISSUED: 'WERE_PRN_OR_PERN_ISSUED_ON_THIS_WASTE',
  RECEIVED_TONNAGE: 'TONNAGE_RECEIVED_FOR_RECYCLING',
  SENT_ON_TONNAGE: 'TONNAGE_OF_UK_PACKAGING_WASTE_SENT_ON'
})
